[Editor]
FontFamily = "Consolas"
FontSize = 10
CursorBlink = true
IndentGuide = true
StartMaximizedWindow = true
ExtTabline  = false
ExtCmdline = false
ExtMessages = false
ExtPopupmenu = false

[Tabline]
Visible = false

[ScrollBar]
Visible = false

[ActivityBar]
Visible = false
